on:
  workflow_dispatch:

jobs:
  bowtie-job:
    name: Bowtie Validation
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
      
      - name: Checkout Bowtie Implementations
        uses: actions/checkout@v3.5.2
        with:
          repository: bowtie-json-schema/bowtie
          path: bowtie
        
      - name: Bowtie Setup
        uses: bowtie-json-schema/bowtie@v2023.05.12
        
      - name: Test
        run: find bowtie/implementations -mindepth 1 -maxdepth 1 -type d
        
      - name: Run Validation
        run: |
           bowtie suite $(find bowtie/implementations -mindepth 1 -maxdepth 1 -type d | sed 's/.*\/implementations\//-i /') ./validation/bowtie_test.json | bowtie report
           
      - name: Visualize Report
        uses: pavi2410/html-preview-action@v2
        with:
          html_file: bowtie-report.html
