name: Bowtie Validation
on:
  workflow_dispatch:

jobs:
  bowtie-job:
    name: Bowtie Validation
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
      
      - name: Checkout Bowtie Implementations
        uses: actions/checkout@v3.5.2
        with:
          repository: bowtie-json-schema/bowtie
          path: bowtie
        
      - name: Bowtie Setup
        uses: bowtie-json-schema/bowtie@v2023.05.12
        
      - name: Run Validation
        run: |
           bowtie validate $(find bowtie/implementations -mindepth 1 -maxdepth 1 -type d | sed 's/.*\/implementations\//-i /') -D draft7 validation/td-json-schema-validation.json validation/resources/minTD.td.json | bowtie report
           
      - name: Visualize Report
        run: cat bowtie-report.html
